### ISSUE TITLE
aws.h is missing

### ISSUE THREAD

**Issue by polluks** [DarwinNE/tdttr#1]
AWS2C should be a sub-repo.

**Comment by DarwinNE** [comment]
I will fix this (I'll have a look at submodules). For the moment, you can find all the files you need (aws.h, systemd.h, loadsave.c, etc...) as provided by AWS2C.

**Comment by polluks** [comment]
I see, it's a fresh repo :-)
By the way do you know the vbcc cross-compiler?
http://sun.hasenbraten.de/vbcc/

**Comment by DarwinNE** [comment]
I think I tried it at one moment. BTW, I just added the Amiga target, I still have to document which cross compiler I'm using. I tried two ports of gcc, but one gave me issues.

**Comment by polluks** [comment]
Good to know. BTW vbcc always outputs native executables, no need to convert anything.
Did I mention my Amiga port? http://aminet.net/package/game/edit/aws2c

**Comment by DarwinNE** [comment]
That's cool! Maybe, you can indicate https://github.com/DarwinNE/aws2c as the URL for the project, that may be more precise.

**Comment by DarwinNE** [comment]
I am now using this project as a module of https://github.com/DarwinNE/aws2c

That should do, as the build scripts here are built to work this way.
